### ISSUE TITLE
Error on patch 88

### ISSUE THREAD

**Issue by AntiScrewdriver** [tsunpot/channel-switch-command#2]
![image](https://user-images.githubusercontent.com/47073195/71217288-208a0d80-2322-11ea-82a4-2231dba6a5e4.png)

[tera-data-parser] Error: code not known for message "C_SELECT_CHANNEL"
and
Error: [protocol] write ("C_SELECT_CHANNEL"): invalid code "undefined"'

**Comment by tsunpot** [comment]
I have stopped support for all my mods. Ask someone else to do it.
